# This file was generated by GoReleaser. DO NOT EDIT.
cask "andromeda" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "b84f6cecbb3c9a82380f9a8ce36d40e908f96ec7b49e1e6de664beb63c69eaf1"
      url "https://github.com/datamaia/andromeda/releases/download/v#{version}/andromeda_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "939317fd506630ceb2d323b2966b7c31f2c3ded5d6dad679d2ebc7bdba8d9840"
      url "https://github.com/datamaia/andromeda/releases/download/v#{version}/andromeda_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4ae1a70a08230df423983948ced9f88c81d945497a2db22d1858c916712d9552"
      url "https://github.com/datamaia/andromeda/releases/download/v#{version}/andromeda_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a92fdd2ea53a2f6363802bedf5076ec6d5d8455a9477701e517e9b986a9ef39c"
      url "https://github.com/datamaia/andromeda/releases/download/v#{version}/andromeda_#{version}_linux_arm64.tar.gz"
    end
  end

  name "andromeda"
  desc "Your terminal companion for shipping great software."
  homepage "https://github.com/datamaia/andromeda"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "andromeda"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/andromeda"]
    end
  end

  # No zap stanza required

end
