# This file was generated by GoReleaser. DO NOT EDIT.
cask "andromeda" do
  version "0.1.12"

  on_macos do
    on_intel do
      sha256 "5c75e96cffafb65acd5f20e16caebabad23f7f7727c70f54145b6f00bbc48003"
      url "https://github.com/datamaia/andromeda/releases/download/v#{version}/andromeda_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "30888a339f66699c4844a1edc5f27bb4c9ac13086fc0abfb7ff71b4c4f1d6bda"
      url "https://github.com/datamaia/andromeda/releases/download/v#{version}/andromeda_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8afcc44876bc16ec308a1ca100504aa1a4bdf1a47a7de91985b9450663d0c200"
      url "https://github.com/datamaia/andromeda/releases/download/v#{version}/andromeda_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "01fe0f4602d966a14ac8a3048f926829976b6f030a52756187c089c38ea443d8"
      url "https://github.com/datamaia/andromeda/releases/download/v#{version}/andromeda_#{version}_linux_arm64.tar.gz"
    end
  end

  name "andromeda"
  desc "Your terminal companion for shipping great software."
  homepage "https://github.com/datamaia/andromeda"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "andromeda"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/andromeda"]
    end
  end

  # No zap stanza required

end
