# This file was generated by GoReleaser. DO NOT EDIT.
cask "andromeda" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "18d7f5fb9a738c41d02c4affac96e6c1bb65654beed30525a04d2b68c7d2b7e8"
      url "https://github.com/datamaia/andromeda/releases/download/v#{version}/andromeda_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7477b22591db2a0dfa6272f27987009c11c2fc64f92b1c85ebe47bec4710a6df"
      url "https://github.com/datamaia/andromeda/releases/download/v#{version}/andromeda_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ee08aded4a8d03e4fd83db512454afa4a2987a9ef2d4075b78cd2708a491c6ba"
      url "https://github.com/datamaia/andromeda/releases/download/v#{version}/andromeda_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2261cfebf334a5850ec9eaa1d5bbd1fbe780aca23775d9f9a386b8c851093dc4"
      url "https://github.com/datamaia/andromeda/releases/download/v#{version}/andromeda_#{version}_linux_arm64.tar.gz"
    end
  end

  name "andromeda"
  desc "Your terminal companion for shipping great software."
  homepage "https://github.com/datamaia/andromeda"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "andromeda"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/andromeda"]
    end
  end

  # No zap stanza required

end
